### ISSUE TITLE
Yii 2

### ISSUE THREAD

**Issue by farmani** [oncesk/yii-node-socket#24]
the idea behind this ext is great I think if you have any idea to port it for yii 2?
you can count on me if you need any help.

**Comment by BambangSinaga** [comment]
hi,
has this extension integrate with yii2?
I have problem when start server. if I execute "yii" command on console, it seems list node-socket command also.
- migrate                      Manages application migrations.
    migrate/create             Creates a new migration.
    migrate/down               Downgrades the application by reverting old migra
tions.
    migrate/history            Displays the migration history.
    migrate/mark               Modifies the migration history to the specified v
ersion.
    migrate/new                Displays the un-applied new migrations.
    migrate/redo               Redoes the last few migrations.
    migrate/to                 Upgrades or downgrades till the specified version
.
    migrate/up (default)       Upgrades the application by applying new migratio
ns.

- node-socket                  Created by JetBrains PhpStorm.
    node-socket/get-pid
    node-socket/restart
    node-socket/start
    node-socket/stop


To see the help of each command, enter:

  yii help <command-name>

but, when I execute "yii node-socket" command in console, its thrown error with message C:\xampp\htdocs\ned_web>yii node-socket
Error: Unknown command "node-socket".

would you like to help me?

**Comment by oncesk** [comment]
hi, yes extension is integrated with Yii2

try to use
```bash
$> yii node-socket/start
```

**Comment by BambangSinaga** [comment]
I do..
but thrown this error
C:\xampp\htdocs\ned_web>yii node-socket/start
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method
: YiiNodeSocket\NodeSocketCommand::usageError()'

in C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\base\Component.php:285

Stack trace:
#0 C:\xampp\htdocs\ned_web\vendor\oncesk\yii-node-socket\lib\php\NodeSocketComma
nd.php(149): yii\base\Component->__call('usageError', Array)
#1 C:\xampp\htdocs\ned_web\vendor\oncesk\yii-node-socket\lib\php\NodeSocketComma
nd.php(149): YiiNodeSocket\NodeSocketCommand->usageError('Please provide ...')
#2 C:\xampp\htdocs\ned_web\vendor\oncesk\yii-node-socket\lib\php\NodeSocketComma
nd.php(188): YiiNodeSocket\NodeSocketCommand->getComponent()
#3 C:\xampp\htdocs\ned_web\vendor\oncesk\yii-node-socket\lib\php\NodeSocketComma
nd.php(178): YiiNodeSocket\NodeSocketCommand->getPidFile()
#4 C:\xampp\htdocs\ned_web\vendor\oncesk\yii-node-socket\lib\php\NodeSocketComma
nd.php(168): YiiNodeSocket\NodeSocketCommand->updatePid()
#5 C:\xampp\htdocs\ned_web\vendor\oncesk\yii-node-socket\lib\php\NodeSocketComma
nd.php(215): YiiNodeSocket\NodeSocketCommand->getPid()
#6 C:\xampp\htdocs\ned_web\vendor\oncesk\yii-node-socket\lib\php\NodeSocketComma
nd.php(36): YiiNodeSocket\NodeSocketCommand->_start()
#7 [internal function]: YiiNodeSocket\NodeSocketCommand->actionStart()
#8 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\base\InlineAction.php(55): call_u
ser_func_array(Array, Array)
#9 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\base\Controller.php(151): yii\bas
e\InlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\console\Controller.php(91): yii\
base\Controller->runAction('start', Array)
#11 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\base\Module.php(455): yii\consol
e\Controller->runAction('start', Array)
#12 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\console\Application.php(161): yi
i\base\Module->runAction('node-socket/sta...', Array)
#13 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\console\Application.php(137): yi
i\console\Application->runAction('node-socket/sta...', Array)
#14 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\base\Application.php(375): yii\c
onsole\Application->handleRequest(Object(yii\console\Request))
#15 C:\xampp\htdocs\ned_web\yii(31): yii\base\Application->run()
#16 {main}

C:\xampp\htdocs\ned_web>

**Comment by BambangSinaga** [comment]
I have search solution according to error, but nothing answer this problem

**Comment by oncesk** [comment]
do you add command to controllerMap in your console config like its described in configuration instructions?

can you show me you configuration?

**Comment by BambangSinaga** [comment]
yes,

This is my all console configuration
<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'console\controllers',
    'controllerMap' => [
        'node-socket' => '\YiiNodeSocket\NodeSocketCommand',
    ],
    'components' => [
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
    ],
    'params' => $params,
];

**Comment by BambangSinaga** [comment]
is there any wrong with my console configuration?

**Comment by oncesk** [comment]
one moment please i fix it now

**Comment by BambangSinaga** [comment]
okay,
tks before..

**Comment by oncesk** [comment]
you need to add nodeSocket component configuration to your config files

**Comment by BambangSinaga** [comment]
yes i have copy this config

        'nodeSocket' => [
            'class' => '\YiiNodeSocket\NodeSocket',
            'dbOptions' => '',
            'host' => 'localhost',
            'allowedServerAddresses' => [
                "localhost",
                "127.0.0.1"
            ],
            'origin' => '*:*',
            'sessionVarName' => 'PHPSESSID',
            'port' => 3001,
            'socketLogFile' => '/var/log/node-socket.log',
        ],
to common/config in component section, and add aliases too

**Comment by oncesk** [comment]
setup extension in your composer to 2.0.4 version and update it

**Comment by oncesk** [comment]
with 'dbOptions' => ''  will be error, i already removed it from documentation

**Comment by oncesk** [comment]
please notify me when check it

**Comment by BambangSinaga** [comment]
ok, sure..

**Comment by BambangSinaga** [comment]
when I run "composer update", this happen
C:\xampp\htdocs\ned_web>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing oncesk/yii-node-socket (2.0.3)



  [UnexpectedValueException]
  RecursiveDirectoryIterator::__construct(C:\xampp\htdocs\ned_web\vendor/once
  sk/yii-node-socket\examples\events,C:\xampp\htdocs\ned_web\vendor/oncesk/yi
  i-node-socket\examples\events): Access is denied. (code: 5)


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock]
 [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-
progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
 [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [p
ackagesN]

and when run "yii node-socket/start", thrown error bellow:
C:\xampp\htdocs\ned_web>yii node-socket/start
Exception 'ReflectionException' with message 'Class \YiiNodeSocket\NodeSocketCom
mand does not exist'

in C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\di\Container.php:415

Stack trace:
#0 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\di\Container.php(415): Reflection
Class->__construct('\\YiiNodeSocket\\...')
#1 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\di\Container.php(358): yii\di\Con
tainer->getDependencies('\\YiiNodeSocket\\...')
#2 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\di\Container.php(151): yii\di\Con
tainer->build('\\YiiNodeSocket\\...', Array, Array)
#3 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\BaseYii.php(340): yii\di\Containe
r->get('\\YiiNodeSocket\\...', Array)
#4 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\base\Module.php(508): yii\BaseYii
::createObject('\\YiiNodeSocket\\...', Array)
#5 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\base\Module.php(449): yii\base\Mo
dule->createController('node-socket/sta...')
#6 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\console\Application.php(161): yii
\base\Module->runAction('node-socket/sta...', Array)
#7 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\console\Application.php(137): yii
\console\Application->runAction('node-socket/sta...', Array)
#8 C:\xampp\htdocs\ned_web\vendor\yiisoft\yii2\base\Application.php(375): yii\co
nsole\Application->handleRequest(Object(yii\console\Request))
#9 C:\xampp\htdocs\ned_web\yii(31): yii\base\Application->run()
#10 {main}

**Comment by oncesk** [comment]
seems like composer does not install new version, seems like problem with directory permissions

**Comment by BambangSinaga** [comment]
I have successfull reinstall node-socket
![capture](https://cloud.githubusercontent.com/assets/4920541/8563001/960764f2-2563-11e5-83d8-6f144de069b4.PNG)

and configure my config according to documentation.
But when I start, thrown error like below
![capture2](https://cloud.githubusercontent.com/assets/4920541/8563021/e34052a6-2563-11e5-9855-a4601d9acde0.PNG)

I also have warning when run "npm install command" 
![capture4](https://cloud.githubusercontent.com/assets/4920541/8563101/0f656104-2565-11e5-8d02-6ec2de8325c1.PNG)

and error in this section
![capture3](https://cloud.githubusercontent.com/assets/4920541/8563105/1f9d6b34-2565-11e5-9da2-d986f425e6e6.PNG)

**Comment by oncesk** [comment]
hi, you need to check your configuration nodeSocket component should be in component section, yesterday i setup it from scratch and all works

error throws on 152 line of NodeSocketCommand file you can check it manually, check if component exists in yii service locator

just now i checked npm install command and all components was installed succesfully
i have v0.10.36 and v0.12.6 versions of nodejs

for fixing npm install you can try to remove mongoose lib from package.json which located in lib/js/server/package.json or install python)

before that you can fork extension to your github account

seems like all of that problems because you os is windows :)

**Comment by BambangSinaga** [comment]
I finally successfull start the server
![capture5](https://cloud.githubusercontent.com/assets/4920541/8566969/ebd8b764-258b-11e5-8bfc-9ba69b6b73b7.PNG)
I move nodeSocket component to common config, which before I write it in frontend config. Next, I add this config to common config also
![capture6](https://cloud.githubusercontent.com/assets/4920541/8567055/6fd83292-258c-11e5-831a-bd226ff72c15.PNG)
and start again server, but it says "No Instance(s) Available."
![capture7](https://cloud.githubusercontent.com/assets/4920541/8567077/a2fd2664-258c-11e5-82c0-211247082dfc.PNG)
what should I do?

**Comment by oncesk** [comment]
do you setup all nodejs dependencies?

do you saw nodejs logs which should locates in runtime folder if you are not redefine socketLogFile property?
try to start server manually in folder lib/js/server using this command for log output into console

```sh
$> node server.js
```
and watch, maybe port already in use

**Comment by oncesk** [comment]
i have not ability to check it on windows system)

**Comment by BambangSinaga** [comment]
server start properly
![capture8](https://cloud.githubusercontent.com/assets/4920541/8567575/bc8be9c2-2590-11e5-9180-52536d992bed.PNG)

and it seems log file not created, eventhough I search "node-socket.log" in my yii2 project.
I have configure nodeSocket component log like this
'socketLogFile' => '/var/log/node-socket.log',

**Comment by oncesk** [comment]
seems like all good)
