### ISSUE TITLE
Loadbalancing

### ISSUE THREAD

**Issue by hohvn** [oncesk/yii-node-socket#36]
I have one issue when using load balancing. Please help me

fwrite(): send of 7 bytes failed with errno=32 Broken pipe

/var/www/vtvdigital/dungdetienroi.vtv.vn/moneydrop_node/protected/extensions/yii-node-socket/lib/vendor/elephant.io/lib/ElephantIO/Client.php(244)

232      \* @return boolean
233      _/
234     public function close() {
235         if ($this->fd) {
236             $this->write($this->encode(self::TYPE_DISCONNECT, Payload::OPCODE_CLOSE), false);
237             fclose($this->fd);
238             return true;
239         }
240         return false;
241     }
242 
243     protected function write($data, $sleep = true) {
244         fwrite($this->getSocket(), $data);
245         // wait 100ms before closing connexion
246         if ($sleep) {
247             usleep(100 \* 1000);
248         }
249         return $this;
250     }
251 
252     /_*
253      \* @return mixed
254      \* @throws \RuntimeException
255      */
256     private function getSocket() {

**Comment by cannycookie** [comment]
Hey Hovn, did you get success with Load Balancing?  We have same situation...

**Comment by oncesk** [comment]
hi, your nodejs logs the same like above?

**Comment by cannycookie** [comment]
We haven't tested on 2 servers at same time yet, I'm just trying to understand if it's possible to make it work with a cluster.

**Comment by oncesk** [comment]
its possible, but need some work, your need something like memcache or redis for node synchronization, somewhere i did it

 - socket.io can do it from 1.0 version, your only need add some configuration, but you need to implement you nodejs and php (using elephantio of newer version) logic by yourself
 - implement it in this extension, you need to broadcast packages to all your nodes, i have some code for this purpose
 - does not use loadbalancer for nodejs

maybe in newer versions of socket.io that really simple, i do not watch socket.io changes now

**Comment by cannycookie** [comment]
Thank you Oncesk, we have patched socket.io already.  Will have a play and see what happens.  Any suggestion on best method for autostart.  Upstart seems to be a good solution: http://howtonode.org/deploying-node-upstart-monit

**Comment by oncesk** [comment]
not at all)
