### ISSUE TITLE
Как сохранять данные из сокетов?

### ISSUE THREAD

**Issue by phaeton2040** [oncesk/yii-node-socket#47]
Допустим, есть задача реализовать чат. И есть необходимость сохранять сообщения в БД. Как это можно сделать, используя ваше расширение?

**Comment by oncesk** [comment]
phaeton2040 wrote:
>
> Допустим, есть задача реализовать чат. И есть необходимость сохранять 
> сообщения в БД. Как это можно сделать, используя ваше расширение?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/oncesk/yii-node-socket/issues/47>.
>
добрый день

  - можно модифицировать экстеншн и добавить туда работу с базой и там 
сохранять
  - можно пере отправкой сообщения делать запрос к серверу что бы 
сообщение сохранялось в базу и возвращать то что надо отправить
  - тоже что и первое только отправлять сообщение с сервера, но лучше с 
javascript а

**Comment by phaeton2040** [comment]
Спасибо. Первый вариант более интересен, хотя вряд ли я его смогу быстро реализовать, с nodejs не очень хорошо знаком. 
Второй вариант на мой взгляд не имеет смысла, поскольку нужно два запроса слать. Так что видимо реализовать по long polling методике(
