### ISSUE TITLE
Working only locally

### ISSUE THREAD

**Issue by edugolive** [oncesk/yii-node-socket#49]
I put the project to operate according to specifications.
But only works localhost when I try to access another machine not working.
He tries to read files on http: // localhost: 3001 ... and can not find the files.
What is wrong?

**Comment by oncesk** [comment]
Hi, i do not properly understand your problem, but you can set ip address into php config instead of domain

Can you give me more explanations or details about a problem?

**Comment by edugolive** [comment]
Ok, I've set the config.main and config.console files and it worked perfectly.
I had forgotten to set the config.console.
Now this ok.
Thank you.
