### ISSUE TITLE
Unknown command "node-socket"

### ISSUE THREAD

**Issue by doublehops** [oncesk/yii-node-socket#52]
I am building a site with Yii2 - Basic and have installed yii-node-socket but I get an error when I try `./yii node-socket` that says `Unknown command "node-socket"`.

I have added the required config into config/console.php (also tried config/web.php). I have installed the package via Composer. I'm at a loss at what else I can try.

Edit: Typing just `./yii` will list node-socket as an available command so I feel that I've configured correctly.

**Comment by doublehops** [comment]
I have worked out what is happening. As there is no actionIndex() method, there is no default action to call. Therefore `./yii node-socket/start` is found.

**Comment by oncesk** [comment]
Hi, yes you should use, now i am updating documentation, thank you

```sh
$> yii node-socket/start
```
