### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by KirillRyzhkov** [oncesk/yii-node-socket#54]
Hi, 
I am using basic Yii2 template and can't get command ./yii node-socket/start to run. I am getting error
<strong>Exception 'yii\base\InvalidConfigException' with message 'Unknown component ID: nodeSocket'. </strong> I placed nodeSocket in the components section of the project/config/web.php like

bootstrap' => ['log','nodeSocket'],
'components' => [
    		'nodeSocket' => [
    				'class' => '\YiiNodeSocket\NodeSocket',
    				'host' => 'localhost',
    				'allowedServerAddresses' => [
    						"localhost",
    						"127.0.0.1"
    				],
    				'origin' => '*:*',
    				'sessionVarName' => 'PHPSESSID',
    				'port' => 3001,
    				'socketLogFile' => '/var/log/node-socket.log',
    		],
],
'aliases' => [
		'@YiiNodeSocket' => '@vendor/oncesk/yii-node-socket/lib/php',
		'@nodeWeb' => '@vendor/oncesk/yii-node-socket/lib/js'
	],

<strong>in project/config/console I added</strong>
'controllerMap' => [
		'node-socket' => '\YiiNodeSocket\NodeSocketCommand',
	],

What could be the problem?

**Comment by oncesk** [comment]
Hi, do you speek russian?

Seems like you did not add add nodeSocket component configuration to console config



Отправлено с моего Xiaomi

Сообщение от "KirillRyzhkov <notifications@github.com>":

**Comment by KirillRyzhkov** [comment]
Да, я добавил в <strong>project/config/console.php</strong>
'controllerMap' => [
'node-socket' => '\YiiNodeSocket\NodeSocketCommand',
],
и команда ./yii node-socket/start выполняется, только с ошибкой, или я что-то упустил?

**Comment by oncesk** [comment]
Какая ошибка? Что в логах nodejs?



Отправлено с моего Xiaomi

Сообщение от "KirillRyzhkov <notifications@github.com>":

**Comment by KirillRyzhkov** [comment]
Файл /var/log/node-socket.log не создается почему-то.
А в Терминале такая ошибка 
user:~/workspace/yii2test$ ./yii node-socket/start
Exception 'yii\base\InvalidConfigException' with message 'Unknown component ID: nodeSocket'

in /home/kirill/workspace/yii2test/vendor/yiisoft/yii2/di/ServiceLocator.php:136

Stack trace:
#0 /home/kirill/workspace/yii2test/vendor/oncesk/yii-node-socket/lib/php/NodeSocketCommand.php(152): yii\di\ServiceLocator->get('nodeSocket')
#1 /home/kirill/workspace/yii2test/vendor/oncesk/yii-node-socket/lib/php/NodeSocketCommand.php(196): YiiNodeSocket\NodeSocketCommand->getComponent()
#2 /home/kirill/workspace/yii2test/vendor/oncesk/yii-node-socket/lib/php/NodeSocketCommand.php(186): YiiNodeSocket\NodeSocketCommand->getPidFile()
#3 /home/kirill/workspace/yii2test/vendor/oncesk/yii-node-socket/lib/php/NodeSocketCommand.php(176): YiiNodeSocket\NodeSocketCommand->updatePid()
#4 /home/kirill/workspace/yii2test/vendor/oncesk/yii-node-socket/lib/php/NodeSocketCommand.php(223): YiiNodeSocket\NodeSocketCommand->getPid()
#5 /home/kirill/workspace/yii2test/vendor/oncesk/yii-node-socket/lib/php/NodeSocketCommand.php(36): YiiNodeSocket\NodeSocketCommand->_start()
#6 [internal function]: YiiNodeSocket\NodeSocketCommand->actionStart()
#7 /home/kirill/workspace/yii2test/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /home/kirill/workspace/yii2test/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#9 /home/kirill/workspace/yii2test/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('start', Array)
#10 /home/kirill/workspace/yii2test/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('start', Array)
#11 /home/kirill/workspace/yii2test/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('node-socket/sta...', Array)
#12 /home/kirill/workspace/yii2test/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('node-socket/sta...', Array)
#13 /home/kirill/workspace/yii2test/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /home/kirill/workspace/yii2test/yii(23): yii\base\Application->run()
#15 {main}

**Comment by oncesk** [comment]
Была такая ошибка, правилась уже, в прелоад добавили компонент? Думаю это решит проблему, если конфигурация компонента добавлена в консольный конфиг



Отправлено с моего Xiaomi

Сообщение от "KirillRyzhkov <notifications@github.com>":

**Comment by KirillRyzhkov** [comment]
Спасибо, когда добавил конфиг компонента в консольный конфиг, тогда заработало. То есть из config/web.php убрать настройки компонента? Только есть еще одна небольшая проблема, не создается файл node-socket.log
kirill@klm:~/workspace/yii2test$ ./yii node-socket/start
Compile server
Compile client
Starting server
sh: 1: cannot create /var/log/node-socket.log: Permission denied
Server successfully started
Update pid in file /home/kirill/workspace/yii2test/runtime/socket-transport.pid

**Comment by ramasofficial** [comment]
I'm updating this issue with correct answer:

config/console.php add this configuration to components:
'nodeSocket' => [
		    'class' => '\YiiNodeSocket\NodeSocket',
		    'host' => 'localhost',
		    'allowedServerAddresses' => [
		        "localhost",
		        "127.0.0.1"
		    ],
		    'origin' => '*:*',
		    'sessionVarName' => 'PHPSESSID',
		    'port' => 3001,
		    'socketLogFile' => '/var/log/node-socket.log',
		],

and controller map:

'controllerMap' => [
        'node-socket' => '\YiiNodeSocket\NodeSocketCommand',
    ],

web.php add:
'bootstrap' => ['log', 'nodeSocket'],

and alliasses:
'aliases' => [
        '@YiiNodeSocket' => '@vendor/oncesk/yii-node-socket/lib/php',
        '@nodeWeb' => '@vendor/oncesk/yii-node-socket/lib/js',
    ],

and sockets working.

@oncesk please update it in documentaction with yii2 support

**Comment by oncesk** [comment]
Hello, sure, i will update it, thank you!

чт, 12 нояб. 2020 г. в 16:26, Ramas <notifications@github.com>:
