### ISSUE TITLE
handshake error PHPSESSID 

### ISSUE THREAD

**Issue by ToRvaLDz** [oncesk/yii-node-socket#57]
Hello,
thank you for your work!

Anyway I got an error when I try the example, like :
```
$event = Yii::$app->nodeSocket->getFrameFactory()->createEventFrame();
        $event->setEventName('event.example');
        $event['data'] = array(
            1,
            array(
                'red',
                'black',
                'white'
            )
        );
        $event->send();
```

I got:

```
debug: client authorized
info: handshake authorized 6kKMCtN5oVddD8pirJYT
debug: setting request GET /socket.io/1/websocket/6kKMCtN5oVddD8pirJYT
debug: set heartbeat interval for client 6kKMCtN5oVddD8pirJYT
debug: client authorized for 
debug: websocket writing 1::
debug: client unauthorized for /server
warn: handshake error PHPSESSID is undefined for /server
debug: websocket writing 7::/server:undefined
info: transport end (undefined)
debug: set close timeout for client 6kKMCtN5oVddD8pirJYT
debug: cleared close timeout for client 6kKMCtN5oVddD8pirJYT
debug: cleared heartbeat interval for client 6kKMCtN5oVddD8pirJYT
debug: discarding transport
```

I tried to debug server.js and it seems that the variable data.cookie.PHPSESSID is empty, I also checked the header and it have the PHPSESSID.

I have no problem on js side.

Can you help me please?

**Comment by Rjgoolsby** [comment]
Yii2 doesn't start session automatically. You have to add 
```
$session = new Session;
$session->open();
```

See my comment here https://github.com/oncesk/yii-node-socket/issues/56#issuecomment-133086245

**Comment by ToRvaLDz** [comment]
Thank you it solve the problem!

Da: Rjgoolsby <notifications@github.com>
Rispondi: oncesk/yii-node-socket <reply@reply.github.com>
Data: 20 agosto 2015 at 19:44:05
A: oncesk/yii-node-socket <yii-node-socket@noreply.github.com>
Cc: ToRvaLDz <torvaldz@gmail.com>
Oggetto:  Re: [yii-node-socket] handshake error PHPSESSID (#57)  

Yii2 doesn't start session automatically. You have to add

$session = new Session;
$session->open();

See my comment here #56 (comment)

**Comment by jpodpro** [comment]
this does not solve my problem. if i try creating a new session then i get

> 2016-04-02 22:27:44 [127.0.0.1][1][-][warning][yii\web\Session::init] Session is already started
    in /Users/jpodtbc/Documents/work/yewbeats/www/_protected/vendor/oncesk/yii-node-socket/lib/php/frames/AFrame.php:240
    in /Users/jpodtbc/Documents/work/yewbeats/www/_protected/vendor/oncesk/yii-node-socket/lib/php/frames/AFrame.php:49
    in /Users/jpodtbc/Documents/work/yewbeats/www/_protected/vendor/oncesk/yii-node-socket/lib/php/frames/FrameFactory.php:32
