### ISSUE TITLE
createJQueryFrame for a single user or channel

### ISSUE THREAD

**Issue by ToRvaLDz** [oncesk/yii-node-socket#58]
There's any way to use a createJQueryFrame just to update a single user or channel subscribers page?

Thanks

**Comment by oncesk** [comment]
Hi, you can use as a channel event

Use setChannel method for set channel name


Отправлено с моего Xiaomi

Сообщение от "ToRvaLDz <notifications@github.com>":

**Comment by ToRvaLDz** [comment]
You are my hero, 
thank you very much.
