### ISSUE TITLE
can't emit message from php to client

### ISSUE THREAD

**Issue by sajad-deris** [oncesk/yii-node-socket#68]
hi.
i can emit on javascript and other clients get the message but from php i can't emit my data to user.
my code is this

$event = Yii::$app->nodeSocket->getFrameFactory()->createUserEventFrame();
$event->setUserId($user->id);
$event->setEventName('message');
$event['text'] = 'Hello, how are you?';
$event->send()

**Comment by oncesk** [comment]
Hi, do you have curl installed?
Show me nodejs logs



Отправлено с моего Xiaomi

Сообщение от "sajad-deris <notifications@github.com>":

**Comment by sajad-deris** [comment]
yes. curl it's installed:
```
cURL support  enabled
cURL Information  7.40.0
Age  3
Features
AsynchDNS  Yes
CharConv  No
Debug  No
GSS-Negotiate  No
IDN  Yes
IPv6  Yes
krb4  No
Largefile  Yes
libz  Yes
NTLM  Yes
NTLMWB  No
SPNEGO  Yes
SSL  Yes
SSPI  Yes
TLS-SRP  No
Protocols  dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, pop3, pop3s, rtsp, scp, sftp, smtp, smtps, telnet, tftp
Host  i386-pc-win32
SSL Version  OpenSSL/1.0.1l
ZLib Version  1.2.7.3
libSSH Version  libssh2/1.5.0
```
### nodejs logs:
![nodejs Logs](http://s6.picofile.com/file/8224058918/photo_2015_11_22_01_07_23.jpg
)


### and this browser logs:
![browser logs](http://s6.picofile.com/file/8224059126/photo_2015_11_22_01_07_25.jpg
)

**Comment by oncesk** [comment]
you just need start session before send frame

see https://github.com/oncesk/yii-node-socket/issues/57

**Comment by sajad-deris** [comment]
tank you. it's work on localhost!
now i move files to server, and set subdomain for app . 
when i start the app. socket is start and  listening to socket.mydomain.net:3001
but i got this error in browser console log
```
http://socket.mydomain.net:3001/socket.io/socket.io.js net::ERR_CONNECTION_TIMED_OUT
```
in fact the http://socket.mydomain.net:3001 not available.

in node console have this:
![error] (http://s6.picofile.com/file/8224371468/Capture.PNG)

my php config file is this:
```
'nodeSocket' => [
            'class' => '\YiiNodeSocket\NodeSocket',
            //'dbOptions' => '',
            'host' => 'socket.mydomain.net',
            'allowedServerAddresses' => [
                "socket.mydomain.net",
                "SiteIP",
            ],
            'origin' => '*:*',
            'sessionVarName' => 'PHPSESSID',
            'port' => 3001,
            'socketLogFile' => '/var/log/node-socket.log',
        ],
```

my js config file is this:
```
module.exports = {
    host : 'socket.mydomain.net',
    port : parseInt('3001'),
    origin : ' *:*',
    allowedServers : ["SiteIP","socket.mydomain.net"],
    dbOptions : {"driver":"dummy","config":[]},
    checkClientOrigin : 1,
    sessionVarName : 'PHPSESSID',
    socketLogFile : '/var/log/node-socket.log'
};
```

**Comment by oncesk** [comment]
Try check on which ip socket listen connection, seems like here trouble in your configuration.... Does website works normally?

Сообщение от "sajad-deris <notifications@github.com>":

**Comment by sajad-deris** [comment]
yes my site is work normally, 
just can not connect to the port 
see this image:
![error](http://s3.picofile.com/file/8224383734/photo_2015_11_23_21_16_32.jpg)

**Comment by sajad-deris** [comment]
please help me.

**Comment by sajad-deris** [comment]
no tank its work!!

**Comment by oncesk** [comment]
=)
