### ISSUE TITLE
Git clone url for yii1.1 may be of earlier releases.

### ISSUE THREAD

**Issue by imanilchaudhari** [oncesk/yii-node-socket#71]
On README.md 

$> git clone https://github.com/oncesk/yii-node-socket.git
may be to earlier releases like
$> git clone --branch 2.0.0 https://github.com/oncesk/yii-node-socket.git

this is confusing beginners like me.

**Comment by oncesk** [comment]
hi, do you propose to remove this?

**Comment by ImAnilChaudhari** [comment]
Well, just deserving to get proper documentation only. :)
